In [2]:
pip install pandas as pd

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\Lavanyasathish\AppData\Roaming\Python\Python314\site-packages (2.3.3)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement as (from versions: none)
ERROR: No matching distribution found for as

In [3]:
import pandas as pd
import os


df_raw = pd.read_csv("Luxury_Housing_Bangalore.csv")
print("success")

success

In [38]:
pip install psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Collecting psycopg2-binary
  Using cached psycopg2_binary-2.9.11-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Using cached psycopg2_binary-2.9.11-cp314-cp314-win_amd64.whl (2.8 MB)
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
Note: you may need to restart the kernel to use updated packages.

In [39]:
import psycopg2

mydb = psycopg2.connect(
    host="localhost",
    database="mydb",
    user="postgres",
    password="root",
    port="5432"
)

cursor = mydb.cursor()
print("✅ Connected OK")

✅ Connected OK

In [27]:
df_raw.head()
df_raw.columns
df_raw.tail
df_raw.shape

(100000, 20)

In [20]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Micro_Market          100000 non-null  object
 1   Project_Name          100000 non-null  object
 2   Developer_Name        100000 non-null  object
 3   Unit_Size_Sqft        100000 non-null  float64
 4   Configuration         100000 non-null  object
 5   Ticket_Price_Cr       100000 non-null  float64
 6   Transaction_Type      100000 non-null  object
 7   Buyer_Type            100000 non-null  object
 8   Purchase_Quarter      100000 non-null  object
 9   Connectivity_Score    100000 non-null  float64
 10  Amenity_Score         100000 non-null  float64
 11  Possession_Status     100000 non-null  object
 12  Sales_Channel         100000 non-null  object
 13  NRI_Buyer             100000 non-null  object
 14  Locality_Infra_Score  100000 non-null  float64
 15  Avg_Traffic_Time_Min  100000 non-null  int64
 16  Buyer_Comments        100000 non-null  object
 17  Booking_Flag          100000 non-null  int64
dtypes: float64(5), int64(2), object(11)
memory usage: 13.7+ MB

In [23]:
df_raw.duplicated().sum()

np.int64(0)

In [21]:
df_raw.describe(include="object")

,Micro_Market,Project_Name,Developer_Name,Configuration,Transaction_Type,Buyer_Type,Purchase_Quarter,Possession_Status,Sales_Channel,NRI_Buyer,Buyer_Comments
count,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000
unique,16,500,11,3,2,5,8,3,4,2,10
top,jayanagar,project_0,snn raj,5bhk+,primary,cxo,2024-03-31,under construction,online,no,No Comment
freq,6379,200,9224,33536,50013,20127,12635,33410,25169,50036,18099

In [22]:
df_raw.columns

Index(['Micro_Market', 'Project_Name', 'Developer_Name', 'Unit_Size_Sqft',
       'Configuration', 'Ticket_Price_Cr', 'Transaction_Type', 'Buyer_Type',
       'Purchase_Quarter', 'Connectivity_Score', 'Amenity_Score',
       'Possession_Status', 'Sales_Channel', 'NRI_Buyer',
       'Locality_Infra_Score', 'Avg_Traffic_Time_Min', 'Buyer_Comments',
       'Booking_Flag'],
      dtype='object')

In [ ]:
df_raw.drop_duplicates(subset=["Property_ID"],inplace= True) #drop this propert id because 1lk unique value

In [10]:
df_raw.drop(["Property_ID"],axis=1,inplace=True)

In [27]:
df_raw.head()

,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Booking_Flag
0,sarjapur road,project_0,rmz,4025.0,4bhk,12.750846,primary,nri,2025-03-31,7.990091,5.462863,launch,broker,yes,9.212491,18,loved the amenities!,1
1,indiranagar,project_1,puravankara,5760.0,3bhk,16.292152,primary,other,2024-06-30,4.839024,7.499766,under construction,nri desk,no,7.723898,106,No Comment,1
2,bannerghatta road,project_2,tata housing,7707.0,4bhk,10.517724,primary,hni,2023-12-31,8.131315,8.669227,ready to move,direct,yes,6.985493,113,agent was not responsive.,1
3,bellary road,project_3,embassy,6192.0,3bhk,9.396367,primary,hni,2024-03-31,7.501657,5.720246,ready to move,online,yes,6.100929,106,excellent location!,1
4,koramangala,project_4,snn raj,7147.0,4bhk,15.345392,secondary,hni,2024-12-31,4.525216,8.609649,under construction,broker,no,5.312510,18,too far from my office.,1

In [ ]:
#df_raw["Ticket_Price_Cr"] = df_raw["Ticket_Price_Cr"].fillna(df_raw["Ticket_Price_Cr"].median())

In [ ]:
df_raw["Ticket_Price_Cr"] = df_raw["Ticket_Price_Cr"].fillna(0)

In [ ]:
(df_raw["Ticket_Price_Cr"] == 0).sum()
print(df_raw["Ticket_Price_Cr"].head)

In [33]:

df_raw["Ticket_Price_Cr"] = (
    df_raw["Ticket_Price_Cr"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace(" Cr", "", regex=False) # regex = Flase means no use this Pattern
)

In [34]:
df_raw["Ticket_Price_Cr"] = pd.to_numeric(df_raw["Ticket_Price_Cr"], errors="coerce") #errors="coerce means not able to covert mention NaN

In [35]:
df_raw["Ticket_Price_Cr"].isnull().sum()

np.int64(0)

In [31]:
Cat_data = df_raw.select_dtypes(include=object)

In [ ]:
for col in Cat_data.columns:
    print(df_raw[col].value_counts())

In [32]:
for col in Cat_data:
    df_raw[col] = df_raw[col].str.lower().str.strip().str.title() #change same format

In [ ]:
cat_cols = df_raw.select_dtypes(include='object').columns # space + small spelling mismatch fix

for col in cat_cols:
    df_raw[col] = (
        df_raw[col]
        .str.replace(r"\s+", " ", regex=True)
        .str.title()
    )

In [58]:
df_raw.describe()

,Unit_Size_Sqft,Ticket_Price_Cr,Connectivity_Score,Amenity_Score,Locality_Infra_Score,Avg_Traffic_Time_Min
count,90043.000000,90087.000000,100000.000000,90000.000000,100000.000000,100000.000000
mean,6005.307609,12.719768,6.993001,7.504185,7.499378,67.188020
std,1726.463424,7.669745,1.731699,1.440567,1.443286,30.267763
min,3000.000000,0.660000,4.000031,5.000224,5.000013,15.000000
25%,4512.500000,10.011784,5.495535,6.261394,6.249147,41.000000
50%,5990.000000,12.038456,6.986316,7.499766,7.497347,67.000000
75%,7497.000000,14.097009,8.490617,8.752300,8.751793,93.000000
max,8999.000000,100.000000,9.999970,9.999865,9.999956,119.000000

In [ ]:
median_price = df_raw["Ticket_Price_Cr"].median()
df_raw.loc[df_raw["Ticket_Price_Cr"] < 0, "Ticket_Price_Cr"] = median_price #fix min ticket price nagative value

In [11]:
df_raw.isnull().sum()

Micro_Market            0
Project_Name            0
Developer_Name          0
Unit_Size_Sqft          0
Configuration           0
Ticket_Price_Cr         0
Transaction_Type        0
Buyer_Type              0
Purchase_Quarter        0
Connectivity_Score      0
Amenity_Score           0
Possession_Status       0
Sales_Channel           0
NRI_Buyer               0
Locality_Infra_Score    0
Avg_Traffic_Time_Min    0
Buyer_Comments          0
dtype: int64

In [8]:
df_raw[df_raw["Unit_Size_Sqft"].isnull()]

Empty DataFrame
Columns: [Micro_Market, Project_Name, Developer_Name, Unit_Size_Sqft, Configuration, Ticket_Price_Cr, Transaction_Type, Buyer_Type, Purchase_Quarter, Connectivity_Score, Amenity_Score, Possession_Status, Sales_Channel, NRI_Buyer, Locality_Infra_Score, Avg_Traffic_Time_Min, Buyer_Comments]
Index: []

In [9]:
df_raw["Unit_Size_Sqft"].fillna(df_raw["Unit_Size_Sqft"].median(),inplace=True)

In [73]:
df_raw["Unit_Size_Sqft"].isnull().sum()

np.int64(0)

In [96]:
df_raw["Amenity_Score"].isnull().sum()

np.int64(0)

In [10]:
df_raw["Amenity_Score"].describe()

count    100000.000000
mean          7.503743
std           1.366641
min           5.000224
25%           6.395876
50%           7.499766
75%           8.615671
max           9.999865
Name: Amenity_Score, dtype: float64

In [95]:
df_raw["Amenity_Score"].fillna(df_raw["Amenity_Score"].median(), inplace=True)

In [98]:
df_raw["Buyer_Comments"].fillna("No Comment", inplace=True)

In [11]:
df_raw["Buyer_Comments"].describe

<bound method NDFrame.describe of 0               Loved The Amenities!
1                         No Comment
2          Agent Was Not Responsive.
3                Excellent Location!
4            Too Far From My Office.
                    ...
99995      Underpriced For Location.
99996    Great View From 15Th Floor.
99997                     No Comment
99998                     No Comment
99999                     No Comment
Name: Buyer_Comments, Length: 100000, dtype: object>

In [104]:
df_raw.dtypes

Micro_Market                    object
Project_Name                    object
Developer_Name                  object
Unit_Size_Sqft                 float64
Configuration                   object
Ticket_Price_Cr                float64
Transaction_Type                object
Buyer_Type                      object
Purchase_Quarter        datetime64[ns]
Connectivity_Score             float64
Amenity_Score                  float64
Possession_Status               object
Sales_Channel                   object
NRI_Buyer                       object
Locality_Infra_Score           float64
Avg_Traffic_Time_Min             int64
Buyer_Comments                  object
dtype: object

In [ ]:
df_raw["Purchase_Quarter"] = pd.to_datetime(df_raw["Purchase_Quarter"])

In [25]:
df_raw["Purchase_Quarter"].head()

0   2025-03-31
1   2024-06-30
2   2023-12-31
3   2024-03-31
4   2024-12-31
Name: Purchase_Quarter, dtype: datetime64[ns]

In [16]:
df_raw.tail(10)

,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
99990,mg road,project_490,sobha,3968.0,3bhk,13.819259,primary,hni,2023-06-30,8.196025,6.061669,under construction,broker,no,8.414760,52,agent was not responsive.
99991,jp nagar,project_491,godrej,6339.0,3bhk,12.469538,secondary,startup founder,2024-09-30,5.820541,9.779352,under construction,broker,yes,9.781777,31,will buy after possession.
99992,domlur,project_492,rmz,6831.0,3bhk,19.257859,primary,cxo,2023-12-31,6.065373,7.499766,ready to move,online,yes,7.792512,25,great view from 15th floor.
99993,sarjapur road,project_493,tata housing,7902.0,5bhk+,12.550000,secondary,other,2023-12-31,9.335818,8.489119,under construction,broker,no,8.849914,41,underpriced for location.
99994,hennur road,project_494,snn raj,7300.0,4bhk,20.033649,secondary,nri,2023-09-30,8.267210,8.993696,launch,broker,yes,7.974408,114,No Comment
99995,bellary road,project_495,l&t realty,5550.0,5bhk+,10.185193,primary,nri,2023-12-31,8.379908,7.499766,under construction,online,yes,8.378800,109,underpriced for location.
99996,yelahanka,project_496,l&t realty,3171.0,4bhk,12.272081,secondary,other,2023-12-31,4.716304,6.374069,launch,broker,yes,7.025209,20,great view from 15th floor.
99997,rajajinagar,project_497,prestige,5599.0,4bhk,13.730179,primary,startup founder,2023-09-30,6.193347,7.482473,launch,nri desk,yes,8.984990,63,No Comment
99998,indiranagar,project_498,snn raj,7342.0,4bhk,10.363989,primary,nri,2024-09-30,9.435646,6.369276,under construction,nri desk,yes,7.634717,89,No Comment
99999,hennur road,project_499,embassy,5016.0,5bhk+,10.415617,primary,startup founder,2024-09-30,5.786292,5.284026,launch,broker,yes,6.039943,95,No Comment

In [131]:
df_raw.to_csv("D:\poject 2\Luxury_Housing_Bangalore.csv", index=False)
print("✅ Cleaned CSV saved successfully")

<>:1: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
<>:1: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
C:\Users\Lavanyasathish\AppData\Local\Temp\ipykernel_5720\730616799.py:1: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
  df_raw.to_csv("D:\poject 2\Luxury_Housing_Bangalore.csv", index=False)

✅ Cleaned CSV saved successfully

In [ ]:
df_raw.info()
df_raw.isnull().sum()
df_raw.describe()

In [ ]:
#Feature Engineering

In [ ]:
df_raw['Quarter_Number'] = df_raw['Purchase_Quarter'].dt.quarter  #2023 Q1 sales : add quater colums

In [ ]:
df_raw['Price_per_Sqft'] = (df_raw['Ticket_Price_Cr'] * 10000000) / df_raw['Unit_Size_Sqft'] #property valuation {Ticket_Price_Cr×1,00,00,000​ % unit sqft}
print(df_raw["Price_per_Sqft"]) #add price_per_sqft colum

In [17]:
df_raw['Booking_Flag'] = df_raw['Ticket_Price_Cr'].apply(
    lambda x: 1 if x > 0 else 0 #add booking flag colum booked means 1 if not 0
)

In [19]:
df_raw["Booking_Flag"].value_counts()

Booking_Flag
1    90081
0     9919
Name: count, dtype: int64

In [ ]:
df_raw.drop('NRI_Buyer', axis=1, inplace=True) #NRI_Buyer = Buyer_Type showing this same detailes

In [36]:
df_raw["Booking_Status"] = df_raw["Ticket_Price_Cr"].apply(
    lambda x: "Booked" if x > 0 else "Not Booked"
)

In [37]:
df_raw.head()

,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Booking_Flag,Booking_Status
0,sarjapur road,project_0,rmz,4025.0,4bhk,12.750846,primary,nri,2025-03-31,7.990091,5.462863,launch,broker,yes,9.212491,18,loved the amenities!,1,Booked
1,indiranagar,project_1,puravankara,5760.0,3bhk,16.292152,primary,other,2024-06-30,4.839024,7.499766,under construction,nri desk,no,7.723898,106,No Comment,1,Booked
2,bannerghatta road,project_2,tata housing,7707.0,4bhk,10.517724,primary,hni,2023-12-31,8.131315,8.669227,ready to move,direct,yes,6.985493,113,agent was not responsive.,1,Booked
3,bellary road,project_3,embassy,6192.0,3bhk,9.396367,primary,hni,2024-03-31,7.501657,5.720246,ready to move,online,yes,6.100929,106,excellent location!,1,Booked
4,koramangala,project_4,snn raj,7147.0,4bhk,15.345392,secondary,hni,2024-12-31,4.525216,8.609649,under construction,broker,no,5.312510,18,too far from my office.,1,Booked

In [40]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:root@localhost:5432/mydb")

df_raw.to_sql("luxury_housing", engine, if_exists="replace", index=False)

print("✅ Data inserted into SQL")
print(engine)

✅ Data inserted into SQL
Engine(postgresql://postgres:***@localhost:5432/mydb)

In [130]:
cursor.execute("SELECT 1;")
print(cursor.fetchone())

(1,)